Repository 10up/maps-block-apple, pull requests merged in 2024-08, with the labels that each got.

#220 Add playground and other badges
  README.md
Labels: needs:code-review

#221 Remove generate artifacts step
  .github/workflows/cypress.yml
Labels: needs:feedback

#211 fix update apiVersion of block to version 3
  block.json
  includes/block-assets.php
  package-lock.json
  package.json
  tests/cypress/config.js
  tests/cypress/e2e/block.test.js
Labels: type:enhancement, needs:code-review
